### ISSUE TITLE
Help needed - NextJS in Shared Hosting

### ISSUE THREAD

**Issue by bnbabu55** [imranhsayed/nextjs-woocommerce-restapi#7]
Imran, 

Thanks a ton for creating this wonderful course. I have been a regular follower of most of your courses.

I am working with a client who has a full on WooCommerce site which is very slow and caching has improved performance a little bit but still is not great. I am thinking about suggesting NextJS+WooCommerce site to them, but have some questions before I can do that.

1. First requirement would be, they already have a shared hosting cPanel account that has been paid for long term, they don't want  move away from that account.
2. They also don't want us to create a another CDN account, too many accounts for them to maintain it seems, so even a free Vercel/Netlify account is out of question.
3. Only option I have now is to host both NextJS frontend (in root) and WooCommerce backend (in subdomain or subfoler) in the same account, thinking of NextJS export option.
4. Do you think NextJS export would work for WooCommerce driven site? Or do you think NextJS regular build will work in shared hosting?
5. I have a GatsbyJS WordPress static site hosted in the same fashion, but that does not have WooCommerce though, just plain WP.

Thanks a lot in advance for your input in this regard.

B.

**Comment by imranhsayed** [comment]
You're welcome @bnbabu55 

1. You continue the WordPress hosting with shared hosting.
2. If you don't wish to host the frontend elsewhere, you would need to speak to the client's hosting provider to see what solutions they have to host a node js application.
3. Next.Js export option is not recommended, because it will convert your entire site into static pages, and you would lose onto the key feature of Next.js called Incremental Static regeneration `SS(Re)G`. So if editors update any posts or products in the backend it won't be updated automatically onto the frontend and you would need to rebuild everytime.
4. I doubt shared hosting has the ability to host node.js application. You may need to go for dedicated server. You can check with your service provider to confirm.
5. Explained the same in point 3.

**Comment by bnbabu55** [comment]
Thanks a lot for your suggestions. Will check if client can switch to VPS hosting in order for us to have a NodeJS instance to facilitate NextJS SSR.
